/*
 * Ravimoshark Client API
 * This is an API to interact with Ravimoshark client database. # Introduction This API allow to create, modify and delete addresses and clients. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ravimoshark.apis.client.calls;

import com.ravimoshark.apis.client.ApiException;
import com.ravimoshark.apis.client.model.Addresses;
import com.ravimoshark.apis.client.model.CustomError;
import com.ravimoshark.apis.client.model.Deleted;
import com.ravimoshark.apis.client.model.IdInteger;
import com.ravimoshark.apis.client.model.InlineResponse200;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddressesApi
 */
@Ignore
public class AddressesApiTest {

    private final AddressesApi api = new AddressesApi();

    /**
     * Add one address.
     *
     * Add one address.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addAddressTest() throws ApiException {
        Addresses body = null;
        Addresses response = api.addAddress(body);

        // TODO: test validations
    }
    /**
     * Delete one address.
     *
     * Delete one address.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAddressTest() throws ApiException {
        Long id = null;
        IdInteger response = api.deleteAddress(id);

        // TODO: test validations
    }
    /**
     * Edit one address.
     *
     * Edit one address.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editAddressTest() throws ApiException {
        Addresses body = null;
        Addresses response = api.editAddress(body);

        // TODO: test validations
    }
    /**
     * Get one address.
     *
     * Get one address.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAddressByIdTest() throws ApiException {
        Long id = null;
        Deleted deleted = null;
        Addresses response = api.getAddressById(id, deleted);

        // TODO: test validations
    }
    /**
     * Get all addresses.
     *
     * Get all addresses.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAddressesTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String orderBy = null;
        String filterBy = null;
        Deleted deleted = null;
        Boolean metadata = null;
        String refClient = null;
        InlineResponse200 response = api.getAddresses(skip, limit, orderBy, filterBy, deleted, metadata, refClient);

        // TODO: test validations
    }
}
