/*
 * Ravimoshark Client API
 * This is an API to interact with Ravimoshark client database. # Introduction This API allow to create, modify and delete addresses and clients. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ravimoshark.apis.client.calls;

import com.ravimoshark.apis.client.ApiException;
import com.ravimoshark.apis.client.model.Clients;
import com.ravimoshark.apis.client.model.CustomError;
import com.ravimoshark.apis.client.model.Deleted;
import com.ravimoshark.apis.client.model.IdInteger;
import com.ravimoshark.apis.client.model.InlineResponse2001;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientsApi
 */
@Ignore
public class ClientsApiTest {

    private final ClientsApi api = new ClientsApi();

    /**
     * Add one client.
     *
     * Add one client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addClientTest() throws ApiException {
        Clients body = null;
        Clients response = api.addClient(body);

        // TODO: test validations
    }
    /**
     * Delete one client.
     *
     * Delete one client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClientTest() throws ApiException {
        String refClient = null;
        IdInteger response = api.deleteClient(refClient);

        // TODO: test validations
    }
    /**
     * Edit one client.
     *
     * Edit one client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editClientTest() throws ApiException {
        Clients body = null;
        Clients response = api.editClient(body);

        // TODO: test validations
    }
    /**
     * Get one client.
     *
     * Get one client.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClientByIdTest() throws ApiException {
        String refClient = null;
        Deleted deleted = null;
        Clients response = api.getClientById(refClient, deleted);

        // TODO: test validations
    }
    /**
     * Get all clients.
     *
     * Get all clients.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClientsTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String orderBy = null;
        String filterBy = null;
        Deleted deleted = null;
        Boolean metadata = null;
        String refClient = null;
        InlineResponse2001 response = api.getClients(skip, limit, orderBy, filterBy, deleted, metadata, refClient);

        // TODO: test validations
    }
}
